/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    AtomsFormLogin: typeof import('./../components/atoms/form-login.vue')['default']
    AtomsNavbar: typeof import('./../components/atoms/navbar.vue')['default']
    AtomsUsersForm: typeof import('./../components/atoms/users/form.vue')['default']
    AtomsUsersFormCreate: typeof import('../components/atoms/users/form.vue')['default']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    copy: typeof import('./../components/moleculs/users/modal-update copy.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconRiAddLine: typeof import('~icons/ri/add-line')['default']
    IconRiBox3Line: typeof import('~icons/ri/box3-line')['default']
    IconRiDashboardLine: typeof import('~icons/ri/dashboard-line')['default']
    IconRiDatabase2Line: typeof import('~icons/ri/database2-line')['default']
    IconRiDeleteBin6Line: typeof import('~icons/ri/delete-bin6-line')['default']
    IconRiFileChartLine: typeof import('~icons/ri/file-chart-line')['default']
    IconRiPencilLine: typeof import('~icons/ri/pencil-line')['default']
    IconRiRefreshLine: typeof import('~icons/ri/refresh-line')['default']
    IconRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IconRiUser3Line: typeof import('~icons/ri/user3-line')['default']
    IconRiUserSettingsLine: typeof import('~icons/ri/user-settings-line')['default']
    MoleculsFormModal: typeof import('../components/moleculs/users/modal-create.vue')['default']
    MoleculsModalCreate: typeof import('../components/moleculs/users/modal-create.vue')['default']
    MoleculsUsersModalCreate: typeof import('./../components/moleculs/users/modal-create.vue')['default']
    MoleculsUsersModalDelete: typeof import('./../components/moleculs/users/modal-delete.vue')['default']
    MoleculsUsersModalUpdate: typeof import('./../components/moleculs/users/modal-update.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
