/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/items/': RouteRecordInfo<'/items/', '/items', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/masters': RouteRecordInfo<'/masters', '/masters', Record<never, never>, Record<never, never>, '/masters/' | '/masters/category' | '/masters/item' | '/masters/location'>,
    '/masters/': RouteRecordInfo<'/masters/', '/masters', Record<never, never>, Record<never, never>>,
    '/masters/category': RouteRecordInfo<'/masters/category', '/masters/category', Record<never, never>, Record<never, never>>,
    '/masters/item': RouteRecordInfo<'/masters/item', '/masters/item', Record<never, never>, Record<never, never>>,
    '/masters/location': RouteRecordInfo<'/masters/location', '/masters/location', Record<never, never>, Record<never, never>>,
    '/transactions/': RouteRecordInfo<'/transactions/', '/transactions', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }
}
